language: node_js
sudo: required
before_script: npm install -g polymer-cli
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script: xvfb-run polymer test --module-resolution=node --npm
dist: trusty

